# Generated by Django 5.2.3 on 2025-07-16 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FOSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=100, verbose_name='Nom (Français)')),
                ('nom_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (Arabe)')),
                ('type', models.CharField(choices=[('PS', 'Poste de Santé'), ('CS', 'Centre de Santé'), ('HP', 'Hôpital'), ('DRS', 'Direction Régionale de Santé'), ('DAF', 'Direction Administrative et Financière')], max_length=50)),
                ('code_etablissement', models.CharField(max_length=50, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('adresse', models.CharField(max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('moughataa', models.CharField(max_length=100)),
                ('wilaya', models.CharField(max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'FOSA',
                'verbose_name_plural': 'FOSAs',
                'ordering': ['nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='FOSAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Mise à jour'), ('DELETE', 'Suppression')], max_length=10)),
                ('changes', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fosa.fosa')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique FOSA',
                'verbose_name_plural': 'Historiques FOSA',
                'ordering': ['-timestamp'],
            },
        ),
    ]
